//! Conduit's build script.
//!
//! Two things live here: the module layout `CONDUIT.md` and `AGENTS.md` specify,
//! and the pinned third-party seams behind that layout. Dependencies point
//! downward — `ui` and `workspace` may use `term` and `render`, and `term`,
//! `pty` and `font` know nothing about workspaces, agents or UI.
//!
//! A module joins the build as soon as its source file exists: adding one is
//! adding a `ModuleSpec` row and a file, and nothing else here changes. A row
//! whose file is not written yet declares nothing, because Zig 0.16 hashes the
//! root source file of every declared import — so declaring a module that is
//! not there would be a broken build rather than a pending one.

const std = @import("std");
const builtin = @import("builtin");

/// One Conduit module: the file its root is declared in, and the Conduit
/// modules it may import.
const ModuleSpec = struct {
    name: []const u8,
    source_file: []const u8,
    deps: []const []const u8,
};

/// The module layout, ordered from the leaves upward so the dependency edges
/// read top to bottom.
const modules = [_]ModuleSpec{
    // Leaves. OS-specific code stops at these seams.
    .{ .name = "platform", .source_file = "src/platform.zig", .deps = &.{} },
    .{ .name = "pty", .source_file = "src/pty.zig", .deps = &.{} },
    .{ .name = "config", .source_file = "src/config.zig", .deps = &.{} },
    .{ .name = "font", .source_file = "src/font.zig", .deps = &.{} },
    .{ .name = "link", .source_file = "src/link.zig", .deps = &.{} },
    // TASK-65: the persisted workspace layout, its file and the restore plan.
    .{ .name = "state", .source_file = "src/state.zig", .deps = &.{} },
    // The stamped release version (`-Dversion=`), re-exported from the
    // generated `build_options` module so TASK-69.1's packages can prove it.
    .{ .name = "version", .source_file = "src/version.zig", .deps = &.{} },

    // Terminal engine (libghostty) and the GPU surface both renderers share.
    .{ .name = "theme", .source_file = "src/theme.zig", .deps = &.{"config"} },
    .{ .name = "term", .source_file = "src/term.zig", .deps = &.{"pty"} },
    .{ .name = "render", .source_file = "src/render.zig", .deps = &.{ "font", "platform", "term" } },

    // UI toolkit: primitives and the semantic tree, then input over them.
    .{ .name = "ui", .source_file = "src/ui.zig", .deps = &.{ "font", "render", "term", "theme" } },
    .{ .name = "input", .source_file = "src/input.zig", .deps = &.{ "platform", "term", "ui" } },
    .{ .name = "palette", .source_file = "src/palette.zig", .deps = &.{"input"} },
    // TASK-68: snapshots of the semantic tree served to platform
    // accessibility APIs (AT-SPI2 over D-Bus on Linux).
    .{ .name = "accessibility", .source_file = "src/accessibility.zig", .deps = &.{"ui"} },

    // A session owns a PTY and terminal state; a workspace owns sessions.
    .{ .name = "session", .source_file = "src/session.zig", .deps = &.{ "config", "pty", "term", "theme" } },
    .{ .name = "workspace", .source_file = "src/workspace.zig", .deps = &.{
        "config", "input", "pty", "render", "session", "state", "term", "theme", "ui",
    } },

    // Feature layers over the workspace, and the automation that drives them.
    .{ .name = "agent", .source_file = "src/agent.zig", .deps = &.{
        "config", "input", "session", "theme", "ui", "workspace",
    } },
    .{ .name = "backlog", .source_file = "src/backlog.zig", .deps = &.{
        "config", "input", "theme", "ui", "workspace",
    } },
    .{ .name = "testdriver", .source_file = "src/testdriver.zig", .deps = &.{
        "input", "render", "session", "ui", "workspace",
    } },

    // TASK-60: the token-scoped local control API for harnesses.
    .{ .name = "control", .source_file = "src/control.zig", .deps = &.{"platform"} },

    // The composition root. Its root file is the executable entry point.
    .{ .name = "app", .source_file = "src/main.zig", .deps = &.{
        "accessibility", "agent",   "backlog",  "config",  "control",    "font",      "input",
        "link",          "palette", "platform", "pty",     "render",     "session",   "state",
        "term",          "theme",   "ui",       "version", "testdriver", "workspace",
    } },
};

/// The build module of each entry in `modules`, in the same order, or `null`
/// when the module has no source file yet.
const WiredModules = [modules.len]?*std.Build.Module;

/// The C declaration the SDL3 seam translates. It is generated by the build so
/// the seam needs no committed header file of its own.
const sdl_c_header =
    \\#define SDL_MAIN_HANDLED
    \\#include <SDL3/SDL.h>
;

/// The only Oniguruma declarations terminal search may call. Keeping the C
/// dependency behind this generated seam makes the regex engine an
/// implementation detail of `term` rather than a project-wide import.
const oniguruma_c_header =
    \\#define ONIG_STATIC
    \\#include <oniguruma.h>
;

pub fn build(b: *std.Build) !void {
    const target = b.standardTargetOptions(.{ .default_target = defaultTargetQuery() });
    const optimize = b.standardOptimizeOption(.{});

    const wired = wireConduitModules(b, target, optimize);
    const font_wiring = try wireThirdPartySeams(b, target, optimize, &wired);

    // TASK-69.1: the release version, validated here so a malformed tag fails
    // at configure time, then stamped into every binary that reports it.
    const build_options = b.addOptions();
    build_options.addOption([:0]const u8, "version", resolveVersion(b));
    const build_options_module = build_options.createModule();
    if (wired[moduleIndex("version")]) |version_module| {
        version_module.addImport("build_options", build_options_module);
    }

    const app_spec = modules[moduleIndex("app")];
    const app = wired[moduleIndex("app")] orelse
        fail("the app module's source file {s} is missing", .{app_spec.source_file});
    app.addImport("build_options", build_options_module);

    const exe = b.addExecutable(.{
        .name = "conduit",
        .root_module = app,
    });
    b.installArtifact(exe);
    installLinuxPayload(b, target, optimize);

    // The external driver CLI is a composition root rather than a product
    // module: it consumes the protocol and platform transport without becoming
    // an architectural dependency of the application.
    const conduit_test = b.createModule(.{
        .root_source_file = b.path("src/conduit_test.zig"),
        .target = target,
        .optimize = optimize,
    });
    conduit_test.addImport("platform", wired[moduleIndex("platform")].?);
    conduit_test.addImport("testdriver", wired[moduleIndex("testdriver")].?);
    conduit_test.addImport("build_options", build_options_module);
    const conduit_test_exe = b.addExecutable(.{
        .name = "conduit-test",
        .root_module = conduit_test,
    });
    b.installArtifact(conduit_test_exe);

    // TASK-25's runner is another composition root. It interacts only through
    // the installed conduit-test executable, so scenario code cannot acquire
    // an import edge into application state or accidentally bypass the driver.
    const e2e = b.createModule(.{
        .root_source_file = b.path("e2e/runner.zig"),
        .target = target,
        .optimize = optimize,
    });
    const e2e_exe = b.addExecutable(.{
        .name = "conduit-e2e",
        .root_module = e2e,
    });

    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_cmd.addArgs(args);
    b.step("run", "Run Conduit").dependOn(&run_cmd.step);

    const e2e_cmd = b.addRunArtifact(e2e_exe);
    e2e_cmd.step.dependOn(b.getInstallStep());
    e2e_cmd.addArg(b.getInstallPath(.bin, if (target.result.os.tag == .windows) "conduit-test.exe" else "conduit-test"));
    if (b.args) |args| e2e_cmd.addArgs(args);
    b.step("e2e", "Run the scripted end-to-end scenarios through conduit-test")
        .dependOn(&e2e_cmd.step);

    addTests(b, wired, conduit_test, e2e);
    try addBenchmarks(b, target, optimize, wired, exe, conduit_test_exe, build_options_module);

    if (font_wiring) |wiring| addFontCheck(b, target, optimize, wired[moduleIndex("font")].?, wiring);
}

/// The target `zig build` uses when no `-Dtarget` is given: the host, as usual,
/// except on a Windows host (TASK-5).
///
/// There a fully native target query makes Zig 0.16 compile every C and C++
/// source in the tree (Ghostty's wuffs and SIMD code, zlib, libpng, FreeType,
/// Oniguruma) into errors such as "argument unused during compilation:
/// '-fno-rtlib-defaultlib'" and vector types collapsing to scalars in
/// `mmintrin.h`. The same build succeeds on the same runner once the OS and ABI
/// are named, even with `-Dcpu=native` and the host's exact Windows version, so
/// only the native OS/ABI detection is avoided: the architecture and CPU stay
/// the host's, and the ABI is GNU, which is what native resolves to anyway.
fn defaultTargetQuery() std.Target.Query {
    if (builtin.os.tag != .windows) return .{};
    return .{
        .cpu_arch = builtin.cpu.arch,
        .cpu_model = .native,
        .os_tag = .windows,
        .abi = .gnu,
    };
}

/// Options for every `b.dependency("ghostty", ...)` call, so both resolve to one instance.
///
/// Left empty, Ghostty builds `ghostty-vt` in its own default Debug mode with
/// `slow_runtime_safety` on, which runs `Screen.assertIntegrity` and the page-list
/// integrity checks on every scroll: about 79 µs per linefeed inside a ReleaseSafe
/// Conduit and 1.5 ms inside a Debug one (TASK-72; `seq 1 200000` took 14.6 s in the
/// shipped v0.1.x binaries). The engine is therefore always built at least
/// ReleaseSafe. A Debug Conduit keeps its own safety checks and tests; it only gives
/// up Ghostty's internal integrity asserts, which Conduit's terminal tests do not
/// rely on.
fn ghosttyDependencyOptions(
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) struct { target: std.Build.ResolvedTarget, optimize: std.builtin.OptimizeMode } {
    return .{
        .target = target,
        .optimize = if (optimize == .Debug) .ReleaseSafe else optimize,
    };
}

/// The version a development build reports when no `-Dversion=` is given. It
/// is a valid SemVer prerelease on purpose, so every build passes the same
/// check a tagged release does.
const default_version = "0.0.0-dev";

/// Resolve `-Dversion=` and refuse anything that is not a SemVer 2.0.0 version
/// (`<major>.<minor>.<patch>[-prerelease][+build]`, no leading `v`). The release
/// workflow passes the tag with its `v` stripped, so the binary reports exactly
/// the tag it was built from; a typo fails configuration instead of shipping.
fn resolveVersion(b: *std.Build) [:0]const u8 {
    const raw = b.option(
        []const u8,
        "version",
        "Release version stamped into the binary (default 0.0.0-dev)",
    ) orelse default_version;
    _ = std.SemanticVersion.parse(raw) catch |err| fail(
        "-Dversion='{s}' is not a SemVer 2.0.0 version: expected " ++
            "<major>.<minor>.<patch>[-prerelease][+build] without a leading 'v' ({s})",
        .{ raw, @errorName(err) },
    );
    return b.allocator.dupeZ(u8, raw) catch @panic("OOM");
}

/// Stage the freedesktop metadata and redistributable runtime resources that
/// Linux packages install below their prefix. Other targets retain the exact
/// artifact-only install graph they had before this payload existed.
fn installLinuxPayload(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) void {
    if (target.result.os.tag != .linux) return;

    const desktop_source = b.path("assets/linux/io.github.thowd22.Conduit.desktop");
    const desktop_check = b.addCheckFile(desktop_source, .{ .expected_matches = &.{
        "Type=Application",
        "Exec=conduit",
        "Icon=io.github.thowd22.Conduit",
        "Terminal=false",
        "StartupWMClass=io.github.thowd22.Conduit",
    } });
    desktop_check.setName("validate the Linux desktop entry identity");
    installLinuxFileChecked(
        b,
        desktop_source,
        "share/applications/io.github.thowd22.Conduit.desktop",
        &desktop_check.step,
    );

    // The application icon, rendered from the checked-in master at every
    // freedesktop hicolor size a launcher or task switcher asks for. Each copy
    // is checked to be a PNG whose IHDR declares exactly its directory's size,
    // so a mis-rendered or swapped file fails the build instead of shipping.
    for (linux_icon_sizes) |size| {
        const source = b.path(b.fmt("assets/linux/icons/hicolor/{d}x{d}/apps/io.github.thowd22.Conduit.png", .{ size, size }));
        const check = b.addCheckFile(source, .{ .expected_matches = &.{pngHeader(b, size)} });
        check.setName(b.fmt("validate the Linux {d}x{d} icon", .{ size, size }));
        installLinuxFileChecked(
            b,
            source,
            b.fmt("share/icons/hicolor/{d}x{d}/apps/io.github.thowd22.Conduit.png", .{ size, size }),
            &check.step,
        );
    }

    const payload_files = [_]struct { source: std.Build.LazyPath, destination: []const u8 }{
        .{ .source = b.path(bundled_face_asset), .destination = "share/conduit/fonts/JetBrainsMono-Regular.ttf" },
        .{ .source = b.path("assets/shell-integration/bash/conduit.bash"), .destination = "share/conduit/shell-integration/bash/conduit.bash" },
        .{ .source = b.path("assets/shell-integration/zsh/.zshenv"), .destination = "share/conduit/shell-integration/zsh/.zshenv" },
        .{ .source = b.path("assets/shell-integration/zsh/conduit.zsh"), .destination = "share/conduit/shell-integration/zsh/conduit.zsh" },
        .{ .source = b.path("assets/shell-integration/fish/vendor_conf.d/conduit.fish"), .destination = "share/conduit/shell-integration/fish/vendor_conf.d/conduit.fish" },
        .{ .source = b.path("assets/fonts/LICENSE-JetBrainsMono-OFL-1.1.txt"), .destination = "share/licenses/conduit/JetBrainsMono-OFL-1.1.txt" },
        .{ .source = b.path("assets/THIRD-PARTY-LICENSES/FreeType-FTL.txt"), .destination = "share/licenses/conduit/FreeType-FTL.txt" },
        .{ .source = b.path("assets/THIRD-PARTY-LICENSES/FreeType-LICENSE.TXT"), .destination = "share/licenses/conduit/FreeType-LICENSE.TXT" },
        .{ .source = b.path("assets/THIRD-PARTY-LICENSES/HarfBuzz-COPYING.txt"), .destination = "share/licenses/conduit/HarfBuzz-COPYING.txt" },
        .{ .source = b.path("assets/THIRD-PARTY-LICENSES/Oniguruma-COPYING.txt"), .destination = "share/licenses/conduit/Oniguruma-COPYING.txt" },
        .{ .source = b.path("assets/THIRD-PARTY-LICENSES/zlib-LICENSE.txt"), .destination = "share/licenses/conduit/zlib-LICENSE.txt" },
        .{ .source = b.path("assets/THIRD-PARTY-LICENSES/libpng-LICENSE.txt"), .destination = "share/licenses/conduit/libpng-LICENSE.txt" },
        .{ .source = b.path("assets/fonts/LICENSE-NerdFonts.txt"), .destination = "share/licenses/conduit/NerdFonts-LICENSE.txt" },
        .{ .source = b.path("assets/fonts/NerdFonts-license-audit.md"), .destination = "share/licenses/conduit/NerdFonts-license-audit.md" },
        .{ .source = b.path("LICENSE"), .destination = "share/licenses/conduit/LICENSE" },
        .{ .source = b.dependency("ghostty", ghosttyDependencyOptions(target, optimize)).path("LICENSE"), .destination = "share/licenses/conduit/Ghostty-LICENSE" },
        .{ .source = b.dependency("sdl", .{ .target = target, .optimize = optimize }).path("LICENSE.txt"), .destination = "share/licenses/conduit/SDL-LICENSE.txt" },
        .{ .source = b.dependency("zopengl", .{}).path("LICENSE"), .destination = "share/licenses/conduit/zopengl-LICENSE" },
    };
    for (payload_files) |file| {
        b.getInstallStep().dependOn(&b.addInstallFile(file.source, file.destination).step);
    }
}

/// The freedesktop hicolor sizes the Linux payload installs the application
/// icon at. Each has a checked-in render under `assets/linux/icons/hicolor`.
const linux_icon_sizes = [_]u32{ 16, 22, 24, 32, 48, 64, 128, 256, 512 };

/// The first 24 bytes of a square `size`x`size` PNG: the signature, then the
/// IHDR chunk's length, type, width and height (big-endian). `addCheckFile`
/// only tests for substrings, not prefixes, but the PNG specification puts
/// IHDR immediately after the signature, so finding this run proves both the
/// format and the declared dimensions.
fn pngHeader(b: *std.Build, size: u32) []const u8 {
    var header: [24]u8 = undefined;
    @memcpy(header[0..8], "\x89PNG\r\n\x1a\n");
    std.mem.writeInt(u32, header[8..12], 13, .big);
    @memcpy(header[12..16], "IHDR");
    std.mem.writeInt(u32, header[16..20], size, .big);
    std.mem.writeInt(u32, header[20..24], size, .big);
    return b.allocator.dupe(u8, &header) catch @panic("OOM");
}

fn installLinuxFileChecked(
    b: *std.Build,
    source: std.Build.LazyPath,
    destination: []const u8,
    check: *std.Build.Step,
) void {
    const install = b.addInstallFile(source, destination);
    install.step.dependOn(check);
    b.getInstallStep().dependOn(&install.step);
}

/// Create one build module per Conduit module that has a source file, and point
/// each at the modules it may import. A dependency edge to a module that is not
/// written yet is left unwired: when that module's file lands, the edge comes
/// with it, and until then nothing can `@import` it, so a module that reaches for
/// it fails to compile rather than silently losing the import.
fn wireConduitModules(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) WiredModules {
    var wired: WiredModules = @splat(null);
    for (modules, 0..) |spec, i| {
        if (!sourceExists(b, spec.source_file)) continue;
        wired[i] = b.createModule(.{
            .root_source_file = b.path(spec.source_file),
            .target = target,
            .optimize = optimize,
        });
    }
    for (modules, 0..) |spec, i| {
        const mod = wired[i] orelse continue;
        for (spec.deps) |dep| {
            const dep_mod = wired[moduleIndex(dep)] orelse continue;
            mod.addImport(dep, dep_mod);
        }
    }
    return wired;
}

/// Attach the pinned third-party seams to the Conduit module that owns them:
/// SDL3 and its translated headers behind `platform`, OpenGL behind `render`,
/// and libghostty's terminal engine behind `term`.
///
/// The dependencies are resolved whether or not the module that owns a seam
/// exists yet, so a pin that does not resolve fails the build here instead of in
/// whichever task first imports it. The seams themselves attach only once their
/// module does, which keeps a seam from compiling a library nothing imports.
fn wireThirdPartySeams(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    wired: *const WiredModules,
) !?FontWiring {
    // Backlog decision-1: the terminal engine is the Zig module `ghostty-vt`,
    // never the macOS embedding library.
    const ghostty_vt = b.dependency("ghostty", ghosttyDependencyOptions(target, optimize)).module("ghostty-vt");
    if (wired[moduleIndex("term")]) |term| {
        term.addImport("ghostty-vt", ghostty_vt);

        // Backlog decision-4: exact Ghostty-pinned Oniguruma 6.9.9, built
        // statically and exposed only through Conduit's translated header.
        const oniguruma = try onigurumaLib(b, target, optimize);
        term.addImport("oniguruma-c", onigurumaSeam(b, target, optimize));
        term.linkLibrary(oniguruma);
        term.link_libc = true;
    }

    // Backlog decision-2: OpenGL 3.3 core, resolved through zopengl.
    const zopengl = b.dependency("zopengl", .{}).module("root");
    if (wired[moduleIndex("render")]) |render| render.addImport("zopengl", zopengl);

    // Backlog decision-2: SDL3 for window and input, through the `castholm/SDL`
    // build package plus a thin extern seam Conduit owns.
    const sdl_lib = sdlLib(b, target, optimize);
    if (wired[moduleIndex("platform")]) |platform| {
        platform.addImport("sdl", sdlSeam(b, target, optimize, sdl_lib));
        platform.linkLibrary(sdl_lib);

        // The window icon, as raw 64x64 RGBA8 pixels handed to SDL so task
        // switchers show it before any desktop entry is consulted. Embedded the
        // same way as the bundled face, because `@embedFile` may not reach
        // outside the module's package path.
        if (!sourceExists(b, window_icon_asset)) {
            fail("the window icon {s} is missing from the repository", .{window_icon_asset});
        }
        const icon_files = b.addWriteFiles();
        _ = icon_files.addCopyFile(b.path(window_icon_asset), "window_icon.rgba");
        platform.addAnonymousImport("window-icon", .{
            .root_source_file = icon_files.add("window_icon.zig",
                \\pub const rgba: []const u8 = @embedFile("window_icon.rgba");
            ),
        });
    }

    // The shell-integration scripts, embedded so a shell can be given them
    // without the repository being present at runtime. Same shape as the
    // bundled face: copied into a generated directory beside a Zig file that
    // `@embedFile`s them, because `@embedFile` may not reach outside a module's
    // package path. A missing script fails the build rather than shipping a
    // shell integration with a hole in it.
    if (wired[moduleIndex("app")]) |app| {
        const generated = b.addWriteFiles();
        for (shell_integration_assets) |asset| {
            if (!sourceExists(b, asset.source)) {
                fail("the shell integration script {s} is missing from the repository", .{asset.source});
            }
            _ = generated.addCopyFile(b.path(asset.source), asset.name);
        }
        app.addAnonymousImport("shell-integration", .{
            .root_source_file = generated.add("shell_integration.zig",
                \\pub const bash: []const u8 = @embedFile("conduit.bash");
                \\pub const zsh_env: []const u8 = @embedFile("zshenv");
                \\pub const zsh: []const u8 = @embedFile("conduit.zsh");
                \\pub const fish: []const u8 = @embedFile("conduit.fish");
            ),
        });
    }

    // The font manager: vendored FreeType and HarfBuzz behind the same kind
    // of seam SDL3 gets. FreeType rasterises, HarfBuzz shapes; both are
    // pinned in `build.zig.zon` and built from source because CI installs no
    // system packages.
    if (wired[moduleIndex("font")]) |font| return try wireFontSeams(b, target, optimize, font);
    return null;
}

/// What the font seam consists of, once it has been wired: the two vendored
/// libraries and the one translated module both `font` and the `font-check` step
/// use. They are returned rather than rebuilt per caller, so a second step
/// exercises the same artifacts instead of building its own copies.
const FontWiring = struct {
    freetype: *std.Build.Step.Compile,
    harfbuzz: *std.Build.Step.Compile,
    seam: *std.Build.Module,
};

/// The pinned SDL3 library artifact. Resolved even when no module imports it
/// yet, so the pin is exercised on every configure rather than first use.
fn sdlLib(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) *std.Build.Step.Compile {
    return b.dependency("sdl", .{ .target = target, .optimize = optimize }).artifact("SDL3");
}

/// The Conduit-owned SDL3 seam: SDL's public headers, translated to Zig.
fn sdlSeam(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    sdl_lib: *std.Build.Step.Compile,
) *std.Build.Module {
    const seam = std.Build.Step.TranslateC.create(b, .{
        .root_source_file = b.addWriteFiles().add("sdl3.h", sdl_c_header),
        .target = target,
        .optimize = optimize,
    });
    seam.addIncludePath(sdl_lib.getEmittedIncludeTree());
    return seam.createModule();
}

/// Attach FreeType and HarfBuzz to the font manager: the vendored libraries,
/// and a Conduit-owned seam over each set of headers. This is the same shape
/// as the SDL3 seam — a built library plus translated headers — because the
/// font manager needs exactly what the platform module needs, from a source
/// that resolves the same way on every runner.
fn wireFontSeams(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    font: *std.Build.Module,
) !FontWiring {
    const ft_lib = try freetypeLib(b, target, optimize);
    const hb_lib = try harfbuzzLib(b, target, optimize, ft_lib);

    const font_c = fontSeam(b, target, optimize);
    font.addImport("font-c", font_c);
    font.linkLibrary(ft_lib);
    font.linkLibrary(hb_lib);

    // The bundled fallback face. `@embedFile` may not reach outside the
    // module's own package path, so the asset is copied into the generated
    // directory next to a one-line Zig file that embeds it: that file is the
    // module `font.zig` imports as `bundled-face`.
    const generated = b.addWriteFiles();
    if (!sourceExists(b, bundled_face_asset)) {
        fail("the bundled fallback font {s} is missing from the repository", .{bundled_face_asset});
    }
    _ = generated.addCopyFile(b.path(bundled_face_asset), bundled_face_name);
    font.addAnonymousImport("bundled-face", .{
        .root_source_file = generated.add("bundled_face.zig",
            \\pub const data: []const u8 = @embedFile("JetBrainsMono-Regular.ttf");
        ),
    });

    // The bundled Nerd Font symbols face (TASK-39): the last font-backed link
    // of every fallback chain, so private-use icons draw without a patched
    // font installed. Embedded for the same reason as the face above.
    if (!sourceExists(b, bundled_symbols_asset)) {
        fail("the bundled symbols font {s} is missing from the repository", .{bundled_symbols_asset});
    }
    _ = generated.addCopyFile(b.path(bundled_symbols_asset), bundled_symbols_name);
    font.addAnonymousImport("bundled-symbols", .{
        .root_source_file = generated.add("bundled_symbols.zig",
            \\pub const data: []const u8 = @embedFile("SymbolsNerdFontMono-Regular.ttf");
        ),
    });

    // FreeType is C and HarfBuzz is C++, so anything that links them links
    // both runtimes. They are set on the module rather than left to the
    // compilation because `font` is imported by `ui`, `app` and the test
    // binary, and only the root module of a compilation carries these.
    font.link_libc = true;
    // MSVC cannot mix Zig's bundled libc++ headers with the SDK's, which is
    // why the vendored HarfBuzz is built without libc++ there (see
    // `harfbuzzLib`).
    font.link_libcpp = if (target.result.abi == .msvc) null else true;

    return .{ .freetype = ft_lib, .harfbuzz = hb_lib, .seam = font_c };
}

/// The window icon's raw pixels: 64x64 RGBA8, rendered from the same master as
/// the installed hicolor PNGs. See `src/platform.zig` for how it reaches SDL.
const window_icon_asset = "assets/linux/io.github.thowd22.Conduit-64.rgba";

/// The bundled fallback face, as the build sees it: a file in the repository
/// that is copied and embedded rather than opened at runtime, so that a machine
/// with no fonts installed still renders text. See `assets/fonts/README.md` for
/// its version and licence.
const bundled_face_asset = "assets/fonts/JetBrainsMono-Regular.ttf";
const bundled_face_name = "JetBrainsMono-Regular.ttf";

/// The bundled Nerd Fonts "Symbols Nerd Font Mono" face, embedded like the
/// face above. See `assets/fonts/README.md` for its version and licences.
const bundled_symbols_asset = "assets/fonts/SymbolsNerdFontMono-Regular.ttf";
const bundled_symbols_name = "SymbolsNerdFontMono-Regular.ttf";

/// The shell-integration scripts the app embeds: where each lives in the
/// repository, and the flat name it is copied to beside the generated Zig file
/// that embeds it. See `assets/shell-integration/README.md`.
const shell_integration_assets = [_]struct { source: []const u8, name: []const u8 }{
    .{ .source = "assets/shell-integration/bash/conduit.bash", .name = "conduit.bash" },
    .{ .source = "assets/shell-integration/zsh/.zshenv", .name = "zshenv" },
    .{ .source = "assets/shell-integration/zsh/conduit.zsh", .name = "conduit.zsh" },
    .{ .source = "assets/shell-integration/fish/vendor_conf.d/conduit.fish", .name = "conduit.fish" },
};

/// Build the exact Oniguruma source set and configuration used by the pinned
/// Ghostty tree. The archive is static on every platform, so Linux packages
/// do not depend on a distro's libonig ABI or package naming.
fn onigurumaLib(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) !*std.Build.Step.Compile {
    const upstream = b.dependency("oniguruma", .{});
    const lib = b.addLibrary(.{
        .name = "oniguruma",
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
        .linkage = .static,
    });
    const is_windows = target.result.os.tag == .windows;
    lib.root_module.addIncludePath(upstream.path("src"));
    lib.root_module.addConfigHeader(b.addConfigHeader(.{
        .style = .{ .cmake = upstream.path("src/config.h.cmake.in") },
    }, .{
        .PACKAGE = "oniguruma",
        .PACKAGE_VERSION = "6.9.9",
        .VERSION = "6.9.9",
        .HAVE_ALLOCA = true,
        .HAVE_ALLOCA_H = !is_windows,
        .USE_CRNL_AS_LINE_TERMINATOR = is_windows,
        .HAVE_STDINT_H = true,
        .HAVE_SYS_TIMES_H = !is_windows,
        .HAVE_SYS_TIME_H = !is_windows,
        .HAVE_SYS_TYPES_H = true,
        .HAVE_UNISTD_H = !is_windows,
        .HAVE_INTTYPES_H = true,
        .SIZEOF_INT = target.result.cTypeByteSize(.int),
        .SIZEOF_LONG = target.result.cTypeByteSize(.long),
        .SIZEOF_LONG_LONG = target.result.cTypeByteSize(.longlong),
        .SIZEOF_VOIDP = target.result.ptrBitWidth() / target.result.cTypeBitSize(.char),
    }));

    var flags: std.ArrayList([]const u8) = .empty;
    defer flags.deinit(b.allocator);
    try flags.append(b.allocator, "-DONIG_STATIC");
    if (target.result.abi == .msvc) {
        try flags.appendSlice(b.allocator, &.{
            "-fno-sanitize=undefined",
            "-fno-sanitize-trap=undefined",
        });
    }
    lib.root_module.addCSourceFiles(.{
        .root = upstream.path(""),
        .flags = flags.items,
        .files = oniguruma_srcs,
    });
    return lib;
}

/// Conduit-owned translation of Oniguruma's public header.
fn onigurumaSeam(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) *std.Build.Module {
    const seam = std.Build.Step.TranslateC.create(b, .{
        .root_source_file = b.addWriteFiles().add("conduit_oniguruma.h", oniguruma_c_header),
        .target = target,
        .optimize = optimize,
    });
    seam.addIncludePath(b.dependency("oniguruma", .{}).path("src"));
    return seam.createModule();
}

const oniguruma_srcs: []const []const u8 = &.{
    "src/regerror.c",
    "src/regparse.c",
    "src/regext.c",
    "src/regcomp.c",
    "src/regexec.c",
    "src/reggnu.c",
    "src/regenc.c",
    "src/regsyntax.c",
    "src/regtrav.c",
    "src/regversion.c",
    "src/st.c",
    "src/onig_init.c",
    "src/unicode.c",
    "src/ascii.c",
    "src/utf8.c",
    "src/utf16_be.c",
    "src/utf16_le.c",
    "src/utf32_be.c",
    "src/utf32_le.c",
    "src/euc_jp.c",
    "src/sjis.c",
    "src/iso8859_1.c",
    "src/iso8859_2.c",
    "src/iso8859_3.c",
    "src/iso8859_4.c",
    "src/iso8859_5.c",
    "src/iso8859_6.c",
    "src/iso8859_7.c",
    "src/iso8859_8.c",
    "src/iso8859_9.c",
    "src/iso8859_10.c",
    "src/iso8859_11.c",
    "src/iso8859_13.c",
    "src/iso8859_14.c",
    "src/iso8859_15.c",
    "src/iso8859_16.c",
    "src/euc_tw.c",
    "src/euc_kr.c",
    "src/big5.c",
    "src/gb18030.c",
    "src/koi8_r.c",
    "src/cp1251.c",
    "src/euc_jp_prop.c",
    "src/sjis_prop.c",
    "src/unicode_unfold_key.c",
    "src/unicode_fold1_key.c",
    "src/unicode_fold2_key.c",
    "src/unicode_fold3_key.c",
};

/// The pinned zlib, built from source for libpng. The source list and flags
/// are the pinned Ghostty tree's `pkg/zlib/build.zig`.
fn zlibLib(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) !*std.Build.Step.Compile {
    const upstream = b.dependency("zlib", .{});
    const lib = b.addLibrary(.{
        .name = "z",
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
        .linkage = .static,
    });
    var flags: std.ArrayList([]const u8) = .empty;
    defer flags.deinit(b.allocator);
    try flags.appendSlice(b.allocator, &.{
        "-DHAVE_SYS_TYPES_H",
        "-DHAVE_STDINT_H",
        "-DHAVE_STDDEF_H",
    });
    if (target.result.os.tag != .windows) try flags.append(b.allocator, "-DZ_HAVE_UNISTD_H");
    if (target.result.abi == .msvc) {
        try flags.appendSlice(b.allocator, &.{
            "-fno-sanitize=undefined",
            "-fno-sanitize-trap=undefined",
            "-D_CRT_SECURE_NO_DEPRECATE",
            "-D_CRT_NONSTDC_NO_DEPRECATE",
        });
    }
    lib.root_module.addIncludePath(upstream.path(""));
    lib.root_module.addCSourceFiles(.{ .root = upstream.path(""), .files = zlib_srcs, .flags = flags.items });
    return lib;
}

const zlib_srcs: []const []const u8 = &.{
    "adler32.c",  "compress.c", "crc32.c",   "deflate.c", "gzclose.c",
    "gzlib.c",    "gzread.c",   "gzwrite.c", "inflate.c", "infback.c",
    "inftrees.c", "inffast.c",  "trees.c",   "uncompr.c", "zutil.c",
};

/// The pinned libpng, built from source so FreeType can decode the PNG strikes
/// of colour emoji fonts. Its configuration header is upstream's own
/// `scripts/pnglibconf.h.prebuilt`, copied under the name libpng includes; the
/// architecture-specific SIMD paths are off, exactly as in the pinned Ghostty
/// tree's `pkg/libpng/build.zig`, so one source list builds on every target.
const LibPng = struct {
    lib: *std.Build.Step.Compile,
    /// png.h and pngconf.h.
    include: std.Build.LazyPath,
    /// The generated directory holding pnglibconf.h.
    config: std.Build.LazyPath,
};

fn libpngLib(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zlib: *std.Build.Step.Compile,
) !LibPng {
    const upstream = b.dependency("libpng", .{});
    const zlib_upstream = b.dependency("zlib", .{});
    const config = b.addWriteFiles();
    _ = config.addCopyFile(upstream.path("scripts/pnglibconf.h.prebuilt"), "pnglibconf.h");

    const lib = b.addLibrary(.{
        .name = "png",
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
        .linkage = .static,
    });
    lib.root_module.linkLibrary(zlib);
    if (target.result.os.tag == .linux) lib.root_module.linkSystemLibrary("m", .{});

    var flags: std.ArrayList([]const u8) = .empty;
    defer flags.deinit(b.allocator);
    try flags.appendSlice(b.allocator, &.{
        "-DPNG_ARM_NEON_OPT=0",
        "-DPNG_POWERPC_VSX_OPT=0",
        "-DPNG_INTEL_SSE_OPT=0",
        "-DPNG_MIPS_MSA_OPT=0",
        "-DPNG_MIPS_MMI_OPT=0",
        "-DPNG_LOONGARCH_LSX_OPT=0",
    });
    if (target.result.abi == .msvc) {
        try flags.appendSlice(b.allocator, &.{
            "-fno-sanitize=undefined",
            "-fno-sanitize-trap=undefined",
        });
    }
    lib.root_module.addIncludePath(config.getDirectory());
    lib.root_module.addIncludePath(upstream.path(""));
    lib.root_module.addIncludePath(zlib_upstream.path(""));
    lib.root_module.addCSourceFiles(.{ .root = upstream.path(""), .files = libpng_srcs, .flags = flags.items });
    return .{ .lib = lib, .include = upstream.path(""), .config = config.getDirectory() };
}

const libpng_srcs: []const []const u8 = &.{
    "png.c",      "pngerror.c", "pngget.c",   "pngmem.c",   "pngpread.c",
    "pngread.c",  "pngrio.c",   "pngrtran.c", "pngrutil.c", "pngset.c",
    "pngtrans.c", "pngwio.c",   "pngwrite.c", "pngwtran.c", "pngwutil.c",
};

/// The pinned FreeType, built from source. The source list and the flags are
/// the ones the pinned Ghostty tree's `pkg/freetype/build.zig` uses with its
/// `enable-libpng` option on: libpng (and the zlib it needs) is built from the
/// same pinned sources, because colour emoji fonts store their glyphs as PNG
/// strikes (TASK-39). FreeType keeps its own internal zlib copy for gzip-
/// compressed fonts rather than the system one.
fn freetypeLib(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) !*std.Build.Step.Compile {
    const upstream = b.dependency("freetype", .{ .target = target, .optimize = optimize });
    const lib = b.addLibrary(.{
        .name = "freetype",
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
        .linkage = .static,
    });

    var flags: std.ArrayList([]const u8) = .empty;
    defer flags.deinit(b.allocator);
    try flags.appendSlice(b.allocator, &.{
        "-DFT2_BUILD_LIBRARY",
        "-fno-sanitize=undefined",
        "-DFT_CONFIG_OPTION_USE_PNG=1",
    });
    if (target.result.os.tag != .windows) {
        try flags.appendSlice(b.allocator, &.{
            "-DHAVE_UNISTD_H",
            "-DHAVE_FCNTL_H",
        });
    }

    const zlib = try zlibLib(b, target, optimize);
    const png = try libpngLib(b, target, optimize, zlib);
    lib.root_module.linkLibrary(png.lib);
    lib.root_module.linkLibrary(zlib);
    lib.root_module.addIncludePath(png.config);
    lib.root_module.addIncludePath(png.include);
    lib.root_module.addIncludePath(b.dependency("zlib", .{}).path(""));

    lib.root_module.addIncludePath(upstream.path("include"));
    lib.root_module.addCSourceFiles(.{
        .root = upstream.path(""),
        .files = freetype_srcs,
        .flags = flags.items,
    });

    // `src/svg/svg.c` compiles to nothing without `FT_CONFIG_OPTION_SVG`, but `ftinit.c` still
    // refers to the SVG renderer class, so leaving it out is a link error.
    lib.root_module.addCSourceFile(.{
        .file = upstream.path("src/svg/svg.c"),
        .flags = flags.items,
    });

    // `ftsystem.c` and `ftdebug.c` are the two files upstream keeps per
    // platform. Getting them wrong builds a library that reads font files
    // with the wrong file API, so they are chosen by OS rather than left to
    // the generic copy.
    switch (target.result.os.tag) {
        .linux => {
            lib.root_module.addCSourceFile(.{
                .file = upstream.path("builds/unix/ftsystem.c"),
                .flags = flags.items,
            });
            lib.root_module.addCSourceFile(.{
                .file = upstream.path("src/base/ftdebug.c"),
                .flags = flags.items,
            });
        },
        .windows => {
            lib.root_module.addCSourceFile(.{
                .file = upstream.path("builds/windows/ftsystem.c"),
                .flags = flags.items,
            });
            lib.root_module.addCSourceFile(.{
                .file = upstream.path("builds/windows/ftdebug.c"),
                .flags = flags.items,
            });
            lib.root_module.addWin32ResourceFile(.{ .file = upstream.path("src/base/ftver.rc") });
        },
        else => {
            lib.root_module.addCSourceFile(.{
                .file = upstream.path("src/base/ftsystem.c"),
                .flags = flags.items,
            });
            lib.root_module.addCSourceFile(.{
                .file = upstream.path("src/base/ftdebug.c"),
                .flags = flags.items,
            });
        },
    }

    return lib;
}

/// The pinned HarfBuzz, built from its upstream amalgamation. `hb-ft` is
/// compiled in and FreeType linked, because the shaper reads glyph data
/// through the same face the rasteriser rasterised with.
fn harfbuzzLib(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    ft_lib: *std.Build.Step.Compile,
) !*std.Build.Step.Compile {
    const upstream = b.dependency("harfbuzz", .{ .target = target, .optimize = optimize });
    const lib = b.addLibrary(.{
        .name = "harfbuzz",
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
            .link_libc = true,
            // On MSVC, linking Zig's libc++ puts Zig's bundled C++ headers
            // ahead of the SDK's own and the two sets conflict. The SDK
            // headers are on the include path already, so libc++ is only
            // linked where there is no SDK C++ runtime to conflict with.
            .link_libcpp = target.result.abi != .msvc,
        }),
        .linkage = .static,
    });
    lib.root_module.linkLibrary(ft_lib);

    var flags: std.ArrayList([]const u8) = .empty;
    defer flags.deinit(b.allocator);
    try flags.appendSlice(b.allocator, &.{
        "-DHAVE_STDBOOL_H",
        "-DHAVE_FREETYPE=1",
        // The FreeType this build pins is new enough for the variable-font
        // and transform entry points HarfBuzz probes for at configure time.
        "-DHAVE_FT_GET_VAR_BLEND_COORDINATES=1",
        "-DHAVE_FT_SET_VAR_BLEND_COORDINATES=1",
        "-DHAVE_FT_DONE_MM_VAR=1",
        "-DHAVE_FT_GET_TRANSFORM=1",
    });
    if (target.result.os.tag != .windows) {
        try flags.appendSlice(b.allocator, &.{
            "-DHAVE_UNISTD_H",
            "-DHAVE_SYS_MMAN_H",
            "-DHAVE_PTHREAD=1",
        });
    }
    if (target.result.abi == .msvc) {
        // Zig's ubsan runtime cannot be bundled into a static archive that an
        // external linker consumes (LNK4229), so the archive would be left
        // with unresolved `__ubsan_handle_*` symbols.
        try flags.appendSlice(b.allocator, &.{
            "-fno-sanitize=undefined",
            "-fno-sanitize-trap=undefined",
        });
    }

    lib.root_module.addIncludePath(upstream.path("src"));
    // `hb-ft.h` includes `ft2build.h`, so HarfBuzz is built against FreeType's headers as well as
    // against the FreeType library.
    lib.root_module.addIncludePath(
        b.dependency("freetype", .{ .target = target, .optimize = optimize }).path("include"),
    );
    lib.root_module.addCSourceFile(.{
        .file = upstream.path("src/harfbuzz.cc"),
        .flags = flags.items,
    });

    return lib;
}

/// The Conduit-owned FreeType and HarfBuzz seam: both libraries' public headers,
/// translated together.
///
/// One step, not two, because `hb-ft.h` takes an `FT_Face` and returns a HarfBuzz
/// font built from it: translating the headers separately would give Conduit two
/// unrelated Zig types for the same C struct, and passing a face from one to the
/// other would not compile.
fn fontSeam(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) *std.Build.Module {
    const seam = std.Build.Step.TranslateC.create(b, .{
        .root_source_file = b.addWriteFiles().add("font.h", font_c_header),
        .target = target,
        .optimize = optimize,
    });
    seam.addIncludePath(
        b.dependency("freetype", .{ .target = target, .optimize = optimize }).path("include"),
    );
    seam.addIncludePath(
        b.dependency("harfbuzz", .{ .target = target, .optimize = optimize }).path("src"),
    );
    return seam.createModule();
}

/// The declarations the font manager calls: FreeType's, in the order its own
/// `ft2build.h` requires, then HarfBuzz's shaping API and the FreeType font-funcs
/// bridge that turns an `FT_Face` into a HarfBuzz font.
const font_c_header =
    \\#include <ft2build.h>
    \\#include FT_FREETYPE_H
    \\#include FT_OUTLINE_H
    \\#include FT_BITMAP_H
    \\#include FT_SYNTHESIS_H
    \\#include FT_TRUETYPE_TABLES_H
    \\#include <hb.h>
    \\#include <hb-ft.h>
;

/// Every FreeType translation unit Conduit links. FreeType has no per-feature
/// build to trim here: the drivers are the font formats a terminal renders
/// from, and each is a few thousand lines that the linker's `--gc-sections`
/// style pruning removes for a face that never uses them.
const freetype_srcs: []const []const u8 = &.{
    "src/autofit/autofit.c",
    "src/base/ftbase.c",
    "src/base/ftbbox.c",
    "src/base/ftbdf.c",
    "src/base/ftbitmap.c",
    "src/base/ftcid.c",
    "src/base/ftfstype.c",
    "src/base/ftgasp.c",
    "src/base/ftglyph.c",
    "src/base/ftgxval.c",
    "src/base/ftinit.c",
    "src/base/ftmm.c",
    "src/base/ftotval.c",
    "src/base/ftpatent.c",
    "src/base/ftpfr.c",
    "src/base/ftstroke.c",
    "src/base/ftsynth.c",
    "src/base/fttype1.c",
    "src/base/ftwinfnt.c",
    "src/bdf/bdf.c",
    "src/cache/ftcache.c",
    "src/cff/cff.c",
    "src/cid/type1cid.c",
    "src/gzip/ftgzip.c",
    "src/lzw/ftlzw.c",
    "src/pcf/pcf.c",
    "src/pfr/pfr.c",
    "src/psaux/psaux.c",
    "src/pshinter/pshinter.c",
    "src/psnames/psnames.c",
    "src/raster/raster.c",
    "src/sdf/sdf.c",
    "src/sfnt/sfnt.c",
    "src/smooth/smooth.c",
    "src/truetype/truetype.c",
    "src/type1/type1.c",
    "src/type42/type42.c",
    "src/winfonts/winfnt.c",
};

/// Prove the pinned SDL3 package resolves, translates, links and runs on this
/// toolchain, by building and running a generated source against the same seam
/// `platform` uses. `SDL_GetVersion` needs no window and no display.
///
/// This is not part of the default build: SDL3 is a large C library, and nothing
/// imports it until `platform` does. It stays because decision-2 rests on SDL3
/// working on Zig 0.16, and a pin that stops linking should fail here rather than
/// in whichever task first opens a window.
fn addSdlCheck(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) void {
    const sdl_lib = sdlLib(b, target, optimize);
    const mod = b.createModule(.{
        .root_source_file = b.addWriteFiles().add("sdl_check.zig",
            \\const std = @import("std");
            \\const sdl = @import("sdl");
            \\
            \\pub fn main(init: std.process.Init) !void {
            \\    const encoded = sdl.SDL_GetVersion();
            \\    var buf: [128]u8 = undefined;
            \\    var out = std.Io.File.stdout().writerStreaming(init.io, &buf);
            \\    try out.interface.print("SDL3 seam linked: {d}.{d}.{d}\n", .{
            \\        sdl.SDL_VERSIONNUM_MAJOR(encoded),
            \\        sdl.SDL_VERSIONNUM_MINOR(encoded),
            \\        sdl.SDL_VERSIONNUM_MICRO(encoded),
            \\    });
            \\    try out.interface.flush();
            \\}
        ),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    mod.addImport("sdl", sdlSeam(b, target, optimize, sdl_lib));
    mod.linkLibrary(sdl_lib);

    const exe = b.addExecutable(.{ .name = "conduit-sdl-check", .root_module = mod });
    b.step("sdl-check", "Build and run the SDL3 seam, proving the pin on this toolchain")
        .dependOn(&b.addRunArtifact(exe).step);
}

/// Prove the pinned font stack resolves, loads, shapes, rasterises and caches, by
/// running a generated program against the same `font` module the app imports:
/// a configured family resolved from the system font directories, the bundled
/// face standing in for one that is not installed, the cell metrics of both, and
/// a glyph read back out of the atlas before and after the cache evicts it.
///
/// It is not part of the default build because most of its output depends on the
/// machine's fonts: CI runners install none, so `zig build font-check` is a
/// developer and release-machine step, while the unconditional half of the same
/// behaviour lives in the `font` module's own tests.
fn addFontCheck(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    font: *std.Build.Module,
    wiring: FontWiring,
) void {
    const mod = b.createModule(.{
        .root_source_file = b.addWriteFiles().add("font_check.zig",
            \\const std = @import("std");
            \\const font = @import("font");
            \\const c = @import("font-c");
            \\
            \\/// An FNV-1a hash of the atlas bytes, so a glyph's pixels can be compared
            \\/// across an eviction without printing a screenful of coverage.
            \\fn digest(bytes: []const u8) u64 {
            \\    var hash: u64 = 14695981039346656037;
            \\    for (bytes) |byte| {
            \\        hash ^= byte;
            \\        hash = hash *% 1099511628211;
            \\    }
            \\    return hash;
            \\}
            \\
            \\pub fn main(init: std.process.Init) !void {
            \\    const gpa = init.gpa;
            \\    const home = init.environ_map.get("HOME");
            \\    var buf: [4096]u8 = undefined;
            \\    var out_file = std.Io.File.stdout().writerStreaming(init.io, &buf);
            \\    const out = &out_file.interface;
            \\    defer out_file.interface.flush() catch {};
            \\
            \\    try out.print("vendored HarfBuzz: {s}\n", .{c.hb_version_string()});
            \\
            \\    const directories = try font.systemFontDirectories(gpa, home);
            \\    defer {
            \\        for (directories) |directory| gpa.free(directory);
            \\        gpa.free(directories);
            \\    }
            \\    var catalog = try font.Catalog.scan(init.io, gpa, directories);
            \\    defer catalog.deinit();
            \\    try out.print("scanned {d} font files across {d} system directories\n", .{
            \\        catalog.files.items.len,
            \\        directories.len,
            \\    });
            \\    if (catalog.findFamily("JetBrains Mono")) |found| {
            \\        try out.print("family 'JetBrains Mono' -> {s} ({s} {s})\n", .{
            \\            found.path,
            \\            found.family,
            \\            found.style,
            \\        });
            \\    } else {
            \\        try out.writeAll("family 'JetBrains Mono' is not installed here\n");
            \\    }
            \\    try out.print("family 'Conduit Font That Does Not Exist' -> {s}\n", .{
            \\        if (catalog.findFamily("Conduit Font That Does Not Exist")) |_| "found" else "not found",
            \\    });
            \\
            \\    var resolved = try font.Manager.init(gpa, init.io, .{
            \\        .family = "JetBrains Mono",
            \\        .size = try font.Size.init(14, 1.0),
            \\        .home_dir = home,
            \\    });
            \\    defer resolved.deinit();
            \\    try out.print("resolved: family={s} fallback={} source={s}\n", .{
            \\        resolved.familyName(),
            \\        resolved.isFallback(),
            \\        resolved.sourcePath(),
            \\    });
            \\    try printMetrics(out, "resolved 14px", resolved.metrics());
            \\
            \\    var fallback = try font.Manager.init(gpa, init.io, .{
            \\        .family = "Conduit Font That Does Not Exist",
            \\        .size = try font.Size.init(14, 1.0),
            \\        .home_dir = home,
            \\    });
            \\    defer fallback.deinit();
            \\    try out.print("fallback: family={s} fallback={} source={s}\n", .{
            \\        fallback.familyName(),
            \\        fallback.isFallback(),
            \\        fallback.sourcePath(),
            \\    });
            \\    try printMetrics(out, "fallback 14px", fallback.metrics());
            \\
            \\    // The same bundled face at twice the pixels, to show the metrics come from the face
            \\    // and scale with the size rather than being constants.
            \\    var larger = try font.Manager.init(gpa, init.io, .{
            \\        .family = "Conduit Font That Does Not Exist",
            \\        .size = try font.Size.init(28, 1.0),
            \\        .home_dir = home,
            \\    });
            \\    defer larger.deinit();
            \\    try printMetrics(out, "fallback 28px", larger.metrics());
            \\
            \\    // A run of text through the shaper.
            \\    var run: std.ArrayList(font.ShapedGlyph) = .empty;
            \\    defer run.deinit(gpa);
            \\    try resolved.shape("conduit", &run);
            \\    try out.print("shaped 'conduit' into {d} glyphs:", .{run.items.len});
            \\    for (run.items) |glyph| {
            \\        try out.print(" gid={d}@{d} adv={d:.2}", .{
            \\            glyph.glyph_index,
            \\            glyph.cluster,
            \\            glyph.x_advance_px,
            \\        });
            \\    }
            \\    try out.writeByte('\n');
            \\
            \\    // The cache: rasterise a glyph, ask again, then overflow the atlas
            \\    // and ask a third time. The digest is the glyph's real pixels.
            \\    var cached = try font.Manager.init(gpa, init.io, .{
            \\        .family = "JetBrains Mono",
            \\        .size = try font.Size.init(20, 1.0),
            \\        .home_dir = home,
            \\        .atlas_width_px = 24,
            \\        .atlas_height_px = 24,
            \\    });
            \\    defer cached.deinit();
            \\
            \\    const watched = cached.glyphIndex('g');
            \\    const first = try cached.glyph(watched);
            \\    var first_pixels = try gpa.alloc(u8, @as(usize, first.rect.width) * first.rect.height);
            \\    defer gpa.free(first_pixels);
            \\    const first_len = cached.atlas.copyInto(first, first_pixels);
            \\    try out.print("glyph 'g': gid={d} {d}x{d}px at ({d},{d}) bearing=({d},{d}) advance={d}px digest=0x{x}\n", .{
            \\        watched,
            \\        first.rect.width,
            \\        first.rect.height,
            \\        first.rect.x,
            \\        first.rect.y,
            \\        first.bearing_x_px,
            \\        first.bearing_y_px,
            \\        first.advance_px,
            \\        digest(first_pixels[0..first_len]),
            \\    });
            \\
            \\    _ = try cached.glyph(watched);
            \\    try out.print("second request: hits={d} misses={d} insertions={d} evictions={d}\n", .{
            \\        cached.atlas.stats.hits,
            \\        cached.atlas.stats.misses,
            \\        cached.atlas.stats.insertions,
            \\        cached.atlas.stats.evictions,
            \\    });
            \\
            \\    var codepoint: u21 = '!';
            \\    while (codepoint <= '~' and cached.atlas.isLive(first)) : (codepoint += 1) {
            \\        if (codepoint == 'g') continue;
            \\        _ = cached.glyph(cached.glyphIndex(codepoint)) catch continue;
            \\    }
            \\    try out.print("after filling the atlas: live={} evictions={d}\n", .{
            \\        cached.atlas.isLive(first),
            \\        cached.atlas.stats.evictions,
            \\    });
            \\
            \\    const again = try cached.glyph(watched);
            \\    var after_pixels = try gpa.alloc(u8, first_pixels.len);
            \\    defer gpa.free(after_pixels);
            \\    const after_len = cached.atlas.copyInto(again, after_pixels);
            \\    try out.print("re-rasterised: {d}x{d}px digest=0x{x} identical={}\n", .{
            \\        again.rect.width,
            \\        again.rect.height,
            \\        digest(after_pixels[0..after_len]),
            \\        std.mem.eql(u8, first_pixels, after_pixels),
            \\    });
            \\}
            \\
            \\fn printMetrics(out: *std.Io.Writer, label: []const u8, metrics: font.Metrics) !void {
            \\    try out.print(
            \\        "metrics {s}: cell {d}x{d}px baseline {d}px ascent {d}px descent {d}px\n",
            \\        .{ label, metrics.cell.width_px, metrics.cell.height_px, metrics.baseline_px, metrics.ascent_px, metrics.descent_px },
            \\    );
            \\}
        ),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
        .link_libcpp = if (target.result.abi == .msvc) null else true,
    });
    mod.addImport("font", font);
    mod.addImport("font-c", wiring.seam);
    mod.linkLibrary(wiring.freetype);
    mod.linkLibrary(wiring.harfbuzz);

    const exe = b.addExecutable(.{ .name = "conduit-font-check", .root_module = mod });
    b.step("font-check", "Resolve, load, shape and cache glyphs with the pinned font stack")
        .dependOn(&b.addRunArtifact(exe).step);
}

/// Run the unit tests of every Conduit module that exists. A module's tests live
/// in the module itself, so a module lands in `zig build test` as soon as its
/// file does, with nothing to restructure here.
fn addTests(
    b: *std.Build,
    wired: WiredModules,
    conduit_test: *std.Build.Module,
    e2e: *std.Build.Module,
) void {
    const test_step = b.step("test", "Run the unit tests of every module");
    for (modules, 0..) |spec, i| {
        const mod = wired[i] orelse continue;
        const unit_tests = b.addTest(.{
            .name = b.fmt("{s}-test", .{spec.name}),
            .root_module = mod,
        });
        test_step.dependOn(&b.addRunArtifact(unit_tests).step);
    }

    const conduit_test_tests = b.addTest(.{
        .name = "conduit-test-test",
        .root_module = conduit_test,
    });
    test_step.dependOn(&b.addRunArtifact(conduit_test_tests).step);

    const e2e_tests = b.addTest(.{
        .name = "conduit-e2e-test",
        .root_module = e2e,
    });
    test_step.dependOn(&b.addRunArtifact(e2e_tests).step);

    addBenchTests(b, test_step, wired);
}

/// The optimisation the benchmarks are built with: ReleaseSafe unless
/// `-Doptimize` or `--release` asked for a mode explicitly. A Debug Conduit
/// is never what a budget describes, so a plain `zig build bench` does not
/// measure one; `-Doptimize=Debug` still does when asked for by name.
fn benchOptimize(b: *std.Build, optimize: std.builtin.OptimizeMode) std.builtin.OptimizeMode {
    if (b.user_input_options.contains("optimize") or b.release_mode != .off) return optimize;
    return .ReleaseSafe;
}

/// TASK-67: `zig build bench` and `zig build bench-check`.
///
/// Each benchmark is its own executable so its process memory is its own; the
/// `conduit-bench` runner (`bench/runner.zig`) runs them, echoes their JSON
/// lines, writes `--json=<path>` and, for `bench-check`, enforces
/// `bench/budgets.zig`. When the benchmark mode differs from the main build's,
/// the modules, the third-party seams and the app are wired a second time at
/// that mode, so the startup benchmark launches an optimised `conduit` rather
/// than the installed Debug one. Nothing here joins the default install.
fn addBenchmarks(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    wired: WiredModules,
    exe: *std.Build.Step.Compile,
    conduit_test_exe: *std.Build.Step.Compile,
    build_options_module: *std.Build.Module,
) !void {
    const bench_optimize = benchOptimize(b, optimize);
    var bench_wired = wired;
    var bench_exe = exe;
    var bench_conduit_test = conduit_test_exe;
    if (bench_optimize != optimize) {
        bench_wired = wireConduitModules(b, target, bench_optimize);
        _ = try wireThirdPartySeams(b, target, bench_optimize, &bench_wired);
        bench_wired[moduleIndex("version")].?.addImport("build_options", build_options_module);
        const app = bench_wired[moduleIndex("app")].?;
        app.addImport("build_options", build_options_module);
        bench_exe = b.addExecutable(.{ .name = "conduit", .root_module = app });

        const conduit_test = b.createModule(.{
            .root_source_file = b.path("src/conduit_test.zig"),
            .target = target,
            .optimize = bench_optimize,
        });
        conduit_test.addImport("platform", bench_wired[moduleIndex("platform")].?);
        conduit_test.addImport("testdriver", bench_wired[moduleIndex("testdriver")].?);
        conduit_test.addImport("build_options", build_options_module);
        bench_conduit_test = b.addExecutable(.{ .name = "conduit-test", .root_module = conduit_test });
    }

    const zopengl = b.dependency("zopengl", .{}).module("root");
    const programs = [_]struct { name: []const u8, imports: []const []const u8 }{
        .{ .name = "throughput", .imports = &.{ "term", "render", "font", "platform" } },
        .{ .name = "frame", .imports = &.{ "term", "render", "font", "platform" } },
        .{ .name = "memory", .imports = &.{ "term", "session", "workspace" } },
        .{ .name = "startup", .imports = &.{} },
    };

    const runner_module = b.createModule(.{
        .root_source_file = b.path("bench/runner.zig"),
        .target = target,
        .optimize = bench_optimize,
    });
    const runner = b.addExecutable(.{ .name = "conduit-bench", .root_module = runner_module });

    const bench_run = b.addRunArtifact(runner);
    const check_run = b.addRunArtifact(runner);
    check_run.addArg("--check");
    for ([_]*std.Build.Step.Run{ bench_run, check_run }) |run| {
        // The results depend on the machine and the moment, never only on the
        // inputs, so the step is never cached.
        run.has_side_effects = true;
        run.addPrefixedArtifactArg("--conduit-test=", bench_conduit_test);
        run.addPrefixedArtifactArg("--conduit=", bench_exe);
    }

    for (programs) |program| {
        const module = b.createModule(.{
            .root_source_file = b.path(b.fmt("bench/{s}.zig", .{program.name})),
            .target = target,
            .optimize = bench_optimize,
            .link_libc = true,
        });
        for (program.imports) |name| module.addImport(name, bench_wired[moduleIndex(name)].?);
        module.addImport("zopengl", zopengl);
        const program_exe = b.addExecutable(.{
            .name = b.fmt("conduit-bench-{s}", .{program.name}),
            .root_module = module,
        });
        const prefix = b.fmt("--{s}=", .{program.name});
        bench_run.addPrefixedArtifactArg(prefix, program_exe);
        check_run.addPrefixedArtifactArg(prefix, program_exe);
    }
    if (b.args) |args| {
        bench_run.addArgs(args);
        check_run.addArgs(args);
    }

    b.step("bench", "Run the throughput, frame, memory and startup benchmarks (ReleaseSafe)")
        .dependOn(&bench_run.step);
    b.step("bench-check", "Run the benchmarks and fail when a budget in bench/budgets.zig is breached")
        .dependOn(&check_run.step);
}

/// The benchmark helpers' own unit tests join `zig build test`. They need no
/// display: the GPU helper's test only classifies renderer strings.
fn addBenchTests(b: *std.Build, test_step: *std.Build.Step, wired: WiredModules) void {
    const zopengl = b.dependency("zopengl", .{}).module("root");
    for ([_][]const u8{ "bench/common.zig", "bench/runner.zig", "bench/gpu.zig" }) |source| {
        const module = b.createModule(.{
            .root_source_file = b.path(source),
            .target = wired[moduleIndex("render")].?.resolved_target,
            .optimize = wired[moduleIndex("render")].?.optimize,
            .link_libc = true,
        });
        if (std.mem.eql(u8, source, "bench/gpu.zig")) {
            for ([_][]const u8{ "render", "font", "platform" }) |name| module.addImport(name, wired[moduleIndex(name)].?);
            module.addImport("zopengl", zopengl);
        }
        test_step.dependOn(&b.addRunArtifact(b.addTest(.{
            .name = b.fmt("bench-{s}-test", .{std.fs.path.stem(source)}),
            .root_module = module,
        })).step);
    }
}

/// The row of `modules` a module name occupies. Fails the build on a typo in a
/// module name or a dependency edge, at configure time rather than at compile.
fn moduleIndex(name: []const u8) usize {
    for (modules, 0..) |spec, i| {
        if (std.mem.eql(u8, spec.name, name)) return i;
    }
    fail("unknown Conduit module: {s}", .{name});
}

/// Whether `path`, relative to the repository root, is present.
fn sourceExists(b: *std.Build, path: []const u8) bool {
    b.build_root.handle.access(b.graph.io, path, .{}) catch |err| switch (err) {
        error.FileNotFound => return false,
        else => fail("cannot access '{s}': {s}", .{ path, @errorName(err) }),
    };
    return true;
}

/// Fail the build with a plain message. Every failure raised in this file is a
/// mistake in this file, not in the environment, so it is reported as one.
fn fail(comptime format: []const u8, args: anytype) noreturn {
    std.log.err(format, args);
    std.process.exit(1);
}
